function [Waves,Abs] = importUV(filename)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [SPECTRASUITEDATAFILE,VARNAME2] = IMPORTFILE(FILENAME) Reads data from
%   text file FILENAME for the default selection.
%
%   [SPECTRASUITEDATAFILE,VARNAME2] = IMPORTFILE(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   [SpectraSuiteDataFile,VarName2] = importfile('NDI_20gL_velgrad_00297.txt',18, 2066);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/12/12 10:25:24

fid=fopen(filename);
C=textscan(fid,'%f%f','headerLines',17);
Waves=C{1};
Abs=C{2};
fclose(fid);

end